# Generated by Django 4.1.2 on 2022-10-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('image', models.CharField(max_length=1000)),
                ('release_date', models.DateField()),
                ('lte_exist', models.BooleanField()),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
    ]
